language: go

go:
  - 1.x
  - 1.6
  - 1.7.x
  - 1.8.x
  - tip
  - master

matrix:
  allow_failures:
    - go: tip
    - go: master

install:
    - ./scripts/install_glcoud_emulator.sh
    - source ./scripts/gcloud_pubsub_emulator.sh
    - go get -u github.com/golang/dep/cmd/dep
    - dep ensure

script:
    - go test -v $(go list ./... | grep -v /vendor/)